### ISSUE TITLE
add image?

### ISSUE THREAD

**Issue by kudataz** [dreyacosta/pure-responsive-css3-slider#2]
the demo show 3 images.
but if i add 4 images, th e 4th image not show.. why ?

**Comment by dreyacosta** [comment]
This is an slider without JavaScript so in order to add more images you have to do some maths as I said here on issue #1.

**Comment by kudataz** [comment]
ok sip thxx you :dancer:

**Comment by guyzwyk** [comment]
It rocks. Thx! I use it with Sass preprocessor.
